<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Introduction to Web Accessibility</name>
   <tag></tag>
   <elementGuidId>60473949-7e21-4131-8042-c580ee7f1f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='maincontent']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.section > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96770142-3cdc-4ba6-baf4-f7f33e070ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/intro/</value>
      <webElementGuid>58ec0e1a-27af-4d11-a166-f86bef3ece74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Introduction to Web Accessibility</value>
      <webElementGuid>e2dd895c-e905-451d-8aed-5f69ec003c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;section&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>f2080e49-bbd5-4456-b579-a074c4fbc165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='maincontent']/div/ul/li/a</value>
      <webElementGuid>73ef6aeb-036f-4404-9e58-b88ff2cc5b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Introduction to Web Accessibility')])[2]</value>
      <webElementGuid>d4880adc-8b5d-4b46-a289-5d14564e673b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Resources'])[1]/following::a[1]</value>
      <webElementGuid>16bbec1e-0c72-4e19-9b83-0d3ed9a41b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>f50cae59-954e-48e0-9288-c714dc87b554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WCAG 2 Checklist'])[1]/preceding::a[1]</value>
      <webElementGuid>8f8a7dd6-221d-4fe0-8d83-1c2d5c04b33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section 508 Checklist'])[1]/preceding::a[2]</value>
      <webElementGuid>cacaa856-e80a-485e-968c-1e38bb3a3bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/intro/')]</value>
      <webElementGuid>e9c06b6e-73a6-449c-834d-1cefc0c1826d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>88fb55bb-8f22-41ae-af4a-1684b19c2513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/intro/' and (text() = 'Introduction to Web Accessibility' or . = 'Introduction to Web Accessibility')]</value>
      <webElementGuid>bb5c024f-c1e6-4cfc-8d69-5a622def796c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
